import jsPDF from 'jspdf';

/**
 * Generate and download PDF for a coupon
 * @param {Object} coupon - The coupon object
 */
export const generateCouponPDF = (coupon) => {
  try {
    const doc = new jsPDF();
    
    // Set colors
    const primaryColor = [16, 185, 129]; // Green-500
    const textColor = [31, 41, 55]; // Gray-800
    
    // Add header with background
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');
    
    // Add title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Care Foundation', 105, 20, { align: 'center' });
    
    doc.setFontSize(16);
    doc.text('Coupon Voucher', 105, 30, { align: 'center' });
    
    // Reset text color
    doc.setTextColor(...textColor);
    
    // Add coupon details section
    let yPos = 55;
    
    // Coupon Code (Large and prominent)
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Coupon Code:', 20, yPos);
    doc.setFontSize(24);
    doc.setTextColor(...primaryColor);
    doc.text(coupon.code || 'N/A', 20, yPos + 10);
    doc.setTextColor(...textColor);
    
    yPos += 30;
    
    // Title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Title:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.text(coupon.title || 'Coupon Voucher', 20, yPos + 7);
    
    yPos += 20;
    
    // Description
    if (coupon.description) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Description:', 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      const descriptionLines = doc.splitTextToSize(coupon.description, 170);
      doc.text(descriptionLines, 20, yPos + 7);
      yPos += descriptionLines.length * 7 + 5;
    }
    
    // Value
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Value:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(16);
    const couponValue = typeof coupon.value === 'object' && coupon.value?.amount 
      ? coupon.value.amount 
      : (typeof coupon.value === 'number' ? coupon.value : 0);
    doc.setTextColor(...primaryColor);
    doc.text(`₹${couponValue}`, 20, yPos + 7);
    doc.setTextColor(...textColor);
    
    yPos += 20;
    
    // Validity
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Valid Until:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    const validUntil = coupon.validity?.endDate 
      ? new Date(coupon.validity.endDate).toLocaleDateString('en-IN', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })
      : '90 days from now';
    doc.text(validUntil, 20, yPos + 7);
    
    yPos += 20;
    
    // Status
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Status:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    const status = coupon.status === 'active' ? 'Active' : (coupon.status || 'Active');
    doc.text(status, 20, yPos + 7);
    
    yPos += 20;
    
    // Transaction ID (if available)
    if (coupon.paymentReferences?.transactionId) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Transaction ID:', 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128); // Gray-500
      doc.text(coupon.paymentReferences.transactionId, 20, yPos + 7);
      doc.setTextColor(...textColor);
      yPos += 20;
    }
    
    // Add QR Code placeholder (if QR code data exists)
    if (coupon.qrCode?.data) {
      yPos += 10;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Scan QR Code:', 105, yPos, { align: 'center' });
      // Note: jsPDF doesn't natively support QR codes, but you can add a library like qrcode.js
      // For now, we'll just add a placeholder box
      doc.setDrawColor(...primaryColor);
      doc.setLineWidth(0.5);
      doc.rect(80, yPos + 5, 50, 50);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.text('QR Code', 105, yPos + 30, { align: 'center' });
    }
    
    // Add footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by Care Foundation', 105, pageHeight - 20, { align: 'center' });
    doc.text('www.carefoundation.org', 105, pageHeight - 15, { align: 'center' });
    
    // Generate filename
    const filename = `Coupon_${coupon.code || 'Voucher'}_${new Date().toISOString().split('T')[0]}.pdf`;
    
    // Save PDF
    doc.save(filename);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

